// ----------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code
// EDIT THE CORRESPONDENT .ts FILE INSTEAD

// ----------------------------------------------------------------------------
import cubeRest from '../../src/cube.js';
import {InvalidOrder} from "../base/errors.js";
import { default as protobuf } from '../../../js/src/static_dependencies/protobufjs/light.js';
import { default as Client }  from '../../../js/src/base/ws/Client.js';
// -----------------------------------------------------------------------------

const marketDataProtoDefinitions = {
    "nested": {
        "market_data": {
            "options": {
                "csharp_namespace": "Cube.MarketData",
                "go_package": "go/"
            },
            "nested": {
                "Side": {
                    "values": {
                        "BID": 0,
                        "ASK": 1
                    }
                },
                "KlineInterval": {
                    "values": {
                        "S1": 0,
                        "M1": 1,
                        "M15": 2,
                        "H1": 3,
                        "H4": 4,
                        "D1": 5
                    }
                },
                "MdMessage": {
                    "oneofs": {
                        "inner": {
                            "oneof": [
                                "heartbeat",
                                "summary",
                                "trades",
                                "mboSnapshot",
                                "mboDiff",
                                "mbpSnapshot",
                                "mbpDiff",
                                "kline",
                                "marketStatus"
                            ]
                        },
                        "_marketId": {
                            "oneof": [
                                "marketId"
                            ]
                        }
                    },
                    "fields": {
                        "heartbeat": {
                            "type": "Heartbeat",
                            "id": 1
                        },
                        "summary": {
                            "type": "Summary",
                            "id": 2
                        },
                        "trades": {
                            "type": "Trades",
                            "id": 3
                        },
                        "mboSnapshot": {
                            "type": "MarketByOrder",
                            "id": 4
                        },
                        "mboDiff": {
                            "type": "MarketByOrderDiff",
                            "id": 5
                        },
                        "mbpSnapshot": {
                            "type": "MarketByPrice",
                            "id": 6
                        },
                        "mbpDiff": {
                            "type": "MarketByPriceDiff",
                            "id": 7
                        },
                        "kline": {
                            "type": "Kline",
                            "id": 8
                        },
                        "marketStatus": {
                            "type": "MarketStatus",
                            "id": 10
                        },
                        "marketId": {
                            "type": "uint64",
                            "id": 9,
                            "options": {
                                "proto3_optional": true
                            }
                        }
                    }
                },
                "MarketByPrice": {
                    "fields": {
                        "levels": {
                            "rule": "repeated",
                            "type": "Level",
                            "id": 1
                        },
                        "chunk": {
                            "type": "uint32",
                            "id": 2
                        },
                        "numChunks": {
                            "type": "uint32",
                            "id": 3
                        }
                    },
                    "nested": {
                        "Level": {
                            "fields": {
                                "price": {
                                    "type": "uint64",
                                    "id": 1
                                },
                                "quantity": {
                                    "type": "uint64",
                                    "id": 2
                                },
                                "side": {
                                    "type": "Side",
                                    "id": 3
                                }
                            }
                        }
                    }
                },
                "MarketByPriceDiff": {
                    "fields": {
                        "diffs": {
                            "rule": "repeated",
                            "type": "Diff",
                            "id": 1
                        },
                        "totalBidLevels": {
                            "type": "uint32",
                            "id": 2
                        },
                        "totalAskLevels": {
                            "type": "uint32",
                            "id": 3
                        }
                    },
                    "nested": {
                        "DiffOp": {
                            "values": {
                                "ADD": 0,
                                "REMOVE": 1,
                                "REPLACE": 2
                            }
                        },
                        "Diff": {
                            "fields": {
                                "price": {
                                    "type": "uint64",
                                    "id": 1
                                },
                                "quantity": {
                                    "type": "uint64",
                                    "id": 2
                                },
                                "side": {
                                    "type": "Side",
                                    "id": 3
                                },
                                "op": {
                                    "type": "DiffOp",
                                    "id": 4
                                }
                            }
                        }
                    }
                },
                "MarketByOrder": {
                    "fields": {
                        "orders": {
                            "rule": "repeated",
                            "type": "Order",
                            "id": 1
                        },
                        "chunk": {
                            "type": "uint32",
                            "id": 2
                        },
                        "numChunks": {
                            "type": "uint32",
                            "id": 3
                        }
                    },
                    "nested": {
                        "Order": {
                            "fields": {
                                "price": {
                                    "type": "uint64",
                                    "id": 1
                                },
                                "quantity": {
                                    "type": "uint64",
                                    "id": 2
                                },
                                "exchangeOrderId": {
                                    "type": "uint64",
                                    "id": 3
                                },
                                "side": {
                                    "type": "Side",
                                    "id": 4
                                },
                                "priority": {
                                    "type": "uint64",
                                    "id": 5
                                }
                            }
                        }
                    }
                },
                "MarketByOrderDiff": {
                    "fields": {
                        "diffs": {
                            "rule": "repeated",
                            "type": "Diff",
                            "id": 1
                        },
                        "totalBidLevels": {
                            "type": "uint32",
                            "id": 2
                        },
                        "totalAskLevels": {
                            "type": "uint32",
                            "id": 3
                        },
                        "totalBidOrders": {
                            "type": "uint32",
                            "id": 4
                        },
                        "totalAskOrders": {
                            "type": "uint32",
                            "id": 5
                        }
                    },
                    "nested": {
                        "DiffOp": {
                            "values": {
                                "ADD": 0,
                                "REMOVE": 1,
                                "REPLACE": 2
                            }
                        },
                        "Diff": {
                            "fields": {
                                "price": {
                                    "type": "uint64",
                                    "id": 1
                                },
                                "quantity": {
                                    "type": "uint64",
                                    "id": 2
                                },
                                "exchangeOrderId": {
                                    "type": "uint64",
                                    "id": 3
                                },
                                "side": {
                                    "type": "Side",
                                    "id": 4
                                },
                                "op": {
                                    "type": "DiffOp",
                                    "id": 5
                                },
                                "priority": {
                                    "type": "uint64",
                                    "id": 6
                                }
                            }
                        }
                    }
                },
                "MarketState": {
                    "values": {
                        "UNSPECIFIED": 0,
                        "NORMAL_OPERATION": 1,
                        "CANCEL_ONLY": 2
                    }
                },
                "MarketStatus": {
                    "fields": {
                        "transactTime": {
                            "type": "uint64",
                            "id": 1
                        },
                        "marketState": {
                            "type": "MarketState",
                            "id": 2
                        }
                    }
                },
                "AggressingSide": {
                    "values": {
                        "AGGRESSING_BID": 0,
                        "AGGRESSING_ASK": 1,
                        "AGGRESSING_IMPLIED_BID": 2,
                        "AGGRESSING_IMPLIED_ASK": 3
                    }
                },
                "Trades": {
                    "fields": {
                        "trades": {
                            "rule": "repeated",
                            "type": "Trade",
                            "id": 1
                        }
                    },
                    "nested": {
                        "Trade": {
                            "fields": {
                                "tradeId": {
                                    "type": "uint64",
                                    "id": 1
                                },
                                "price": {
                                    "type": "uint64",
                                    "id": 2
                                },
                                "aggressingSide": {
                                    "type": "AggressingSide",
                                    "id": 3
                                },
                                "restingExchangeOrderId": {
                                    "type": "uint64",
                                    "id": 4
                                },
                                "fillQuantity": {
                                    "type": "uint64",
                                    "id": 5
                                },
                                "transactTime": {
                                    "type": "uint64",
                                    "id": 6
                                },
                                "aggressingExchangeOrderId": {
                                    "type": "uint64",
                                    "id": 7
                                }
                            }
                        }
                    }
                },
                "Summary": {
                    "oneofs": {
                        "_open": {
                            "oneof": [
                                "open"
                            ]
                        },
                        "_close": {
                            "oneof": [
                                "close"
                            ]
                        },
                        "_low": {
                            "oneof": [
                                "low"
                            ]
                        },
                        "_high": {
                            "oneof": [
                                "high"
                            ]
                        }
                    },
                    "fields": {
                        "open": {
                            "type": "uint64",
                            "id": 1,
                            "options": {
                                "proto3_optional": true
                            }
                        },
                        "close": {
                            "type": "uint64",
                            "id": 2,
                            "options": {
                                "proto3_optional": true
                            }
                        },
                        "low": {
                            "type": "uint64",
                            "id": 3,
                            "options": {
                                "proto3_optional": true
                            }
                        },
                        "high": {
                            "type": "uint64",
                            "id": 4,
                            "options": {
                                "proto3_optional": true
                            }
                        },
                        "baseVolumeLo": {
                            "type": "uint64",
                            "id": 5
                        },
                        "baseVolumeHi": {
                            "type": "uint64",
                            "id": 6
                        },
                        "quoteVolumeLo": {
                            "type": "uint64",
                            "id": 7
                        },
                        "quoteVolumeHi": {
                            "type": "uint64",
                            "id": 8
                        }
                    }
                },
                "Kline": {
                    "oneofs": {
                        "_open": {
                            "oneof": [
                                "open"
                            ]
                        },
                        "_close": {
                            "oneof": [
                                "close"
                            ]
                        },
                        "_high": {
                            "oneof": [
                                "high"
                            ]
                        },
                        "_low": {
                            "oneof": [
                                "low"
                            ]
                        }
                    },
                    "fields": {
                        "interval": {
                            "type": "KlineInterval",
                            "id": 1
                        },
                        "startTime": {
                            "type": "uint64",
                            "id": 2
                        },
                        "open": {
                            "type": "uint64",
                            "id": 3,
                            "options": {
                                "proto3_optional": true
                            }
                        },
                        "close": {
                            "type": "uint64",
                            "id": 4,
                            "options": {
                                "proto3_optional": true
                            }
                        },
                        "high": {
                            "type": "uint64",
                            "id": 5,
                            "options": {
                                "proto3_optional": true
                            }
                        },
                        "low": {
                            "type": "uint64",
                            "id": 6,
                            "options": {
                                "proto3_optional": true
                            }
                        },
                        "volumeLo": {
                            "type": "uint64",
                            "id": 7
                        },
                        "volumeHi": {
                            "type": "uint64",
                            "id": 8
                        }
                    }
                },
                "Heartbeat": {
                    "fields": {
                        "requestId": {
                            "type": "uint64",
                            "id": 1
                        },
                        "timestamp": {
                            "type": "uint64",
                            "id": 2
                        }
                    }
                },
                "MdMessages": {
                    "fields": {
                        "messages": {
                            "rule": "repeated",
                            "type": "MdMessage",
                            "id": 1
                        }
                    }
                },
                "AggMessage": {
                    "oneofs": {
                        "inner": {
                            "oneof": [
                                "heartbeat",
                                "topOfBooks",
                                "rateUpdates"
                            ]
                        }
                    },
                    "fields": {
                        "heartbeat": {
                            "type": "Heartbeat",
                            "id": 1
                        },
                        "topOfBooks": {
                            "type": "TopOfBooks",
                            "id": 2
                        },
                        "rateUpdates": {
                            "type": "RateUpdates",
                            "id": 3
                        }
                    }
                },
                "TopOfBook": {
                    "oneofs": {
                        "_bidPrice": {
                            "oneof": [
                                "bidPrice"
                            ]
                        },
                        "_bidQuantity": {
                            "oneof": [
                                "bidQuantity"
                            ]
                        },
                        "_askPrice": {
                            "oneof": [
                                "askPrice"
                            ]
                        },
                        "_askQuantity": {
                            "oneof": [
                                "askQuantity"
                            ]
                        },
                        "_lastPrice": {
                            "oneof": [
                                "lastPrice"
                            ]
                        },
                        "_rolling24hPrice": {
                            "oneof": [
                                "rolling24hPrice"
                            ]
                        },
                        "_impliedBidPrice": {
                            "oneof": [
                                "impliedBidPrice"
                            ]
                        },
                        "_impliedBidQuantity": {
                            "oneof": [
                                "impliedBidQuantity"
                            ]
                        },
                        "_impliedAskPrice": {
                            "oneof": [
                                "impliedAskPrice"
                            ]
                        },
                        "_impliedAskQuantity": {
                            "oneof": [
                                "impliedAskQuantity"
                            ]
                        }
                    },
                    "fields": {
                        "marketId": {
                            "type": "uint64",
                            "id": 1
                        },
                        "transactTime": {
                            "type": "uint64",
                            "id": 2
                        },
                        "bidPrice": {
                            "type": "uint64",
                            "id": 3,
                            "options": {
                                "proto3_optional": true
                            }
                        },
                        "bidQuantity": {
                            "type": "uint64",
                            "id": 4,
                            "options": {
                                "proto3_optional": true
                            }
                        },
                        "askPrice": {
                            "type": "uint64",
                            "id": 5,
                            "options": {
                                "proto3_optional": true
                            }
                        },
                        "askQuantity": {
                            "type": "uint64",
                            "id": 6,
                            "options": {
                                "proto3_optional": true
                            }
                        },
                        "lastPrice": {
                            "type": "uint64",
                            "id": 7,
                            "options": {
                                "proto3_optional": true
                            }
                        },
                        "rolling24hPrice": {
                            "type": "uint64",
                            "id": 8,
                            "options": {
                                "proto3_optional": true
                            }
                        },
                        "impliedBidPrice": {
                            "type": "uint64",
                            "id": 9,
                            "options": {
                                "proto3_optional": true
                            }
                        },
                        "impliedBidQuantity": {
                            "type": "uint64",
                            "id": 10,
                            "options": {
                                "proto3_optional": true
                            }
                        },
                        "impliedAskPrice": {
                            "type": "uint64",
                            "id": 11,
                            "options": {
                                "proto3_optional": true
                            }
                        },
                        "impliedAskQuantity": {
                            "type": "uint64",
                            "id": 12,
                            "options": {
                                "proto3_optional": true
                            }
                        },
                        "marketState": {
                            "type": "MarketState",
                            "id": 13
                        }
                    }
                },
                "TopOfBooks": {
                    "fields": {
                        "tops": {
                            "rule": "repeated",
                            "type": "TopOfBook",
                            "id": 1
                        }
                    }
                },
                "RateUpdate": {
                    "fields": {
                        "assetId": {
                            "type": "uint64",
                            "id": 1
                        },
                        "timestamp": {
                            "type": "uint64",
                            "id": 2
                        },
                        "rate": {
                            "type": "uint64",
                            "id": 3
                        },
                        "side": {
                            "type": "RateUpdateSide",
                            "id": 4
                        }
                    }
                },
                "RateUpdateSide": {
                    "values": {
                        "BASE": 0,
                        "QUOTE": 1
                    }
                },
                "RateUpdates": {
                    "fields": {
                        "updates": {
                            "rule": "repeated",
                            "type": "RateUpdate",
                            "id": 1
                        }
                    }
                },
                "ClientMessage": {
                    "oneofs": {
                        "inner": {
                            "oneof": [
                                "heartbeat",
                                "config"
                            ]
                        }
                    },
                    "fields": {
                        "heartbeat": {
                            "type": "Heartbeat",
                            "id": 1
                        },
                        "config": {
                            "type": "Config",
                            "id": 2
                        }
                    }
                },
                "Config": {
                    "fields": {
                        "mbp": {
                            "type": "bool",
                            "id": 1
                        },
                        "mbo": {
                            "type": "bool",
                            "id": 2
                        },
                        "trades": {
                            "type": "bool",
                            "id": 3
                        },
                        "summary": {
                            "type": "bool",
                            "id": 4
                        },
                        "klines": {
                            "rule": "repeated",
                            "type": "KlineInterval",
                            "id": 5
                        },
                        "marketIds": {
                            "rule": "repeated",
                            "type": "uint64",
                            "id": 6
                        }
                    }
                }
            }
        }
    }
};
const tradeProtoDefinitions = {
    "options": {
        "csharp_namespace": "Cube.Trade",
        "go_package": "go/"
    },
    "nested": {
        "Side": {
            "values": {
                "BID": 0,
                "ASK": 1
            }
        },
        "TimeInForce": {
            "values": {
                "IMMEDIATE_OR_CANCEL": 0,
                "GOOD_FOR_SESSION": 1,
                "FILL_OR_KILL": 2
            }
        },
        "OrderType": {
            "values": {
                "LIMIT": 0,
                "MARKET_LIMIT": 1,
                "MARKET_WITH_PROTECTION": 2
            }
        },
        "SelfTradePrevention": {
            "values": {
                "CANCEL_RESTING": 0,
                "CANCEL_AGGRESSING": 1,
                "ALLOW_SELF_TRADE": 2
            }
        },
        "PostOnly": {
            "values": {
                "DISABLED": 0,
                "ENABLED": 1
            }
        },
        "ConnectionStatus": {
            "values": {
                "READ_ONLY": 0,
                "READ_WRITE": 1
            }
        },
        "Credentials": {
            "fields": {
                "accessKeyId": {
                    "type": "string",
                    "id": 1
                },
                "signature": {
                    "type": "string",
                    "id": 2
                },
                "timestamp": {
                    "type": "uint64",
                    "id": 3
                }
            }
        },
        "OrderRequest": {
            "oneofs": {
                "inner": {
                    "oneof": [
                        "new",
                        "cancel",
                        "modify",
                        "heartbeat",
                        "mc"
                    ]
                }
            },
            "fields": {
                "new": {
                    "type": "NewOrder",
                    "id": 1
                },
                "cancel": {
                    "type": "CancelOrder",
                    "id": 2
                },
                "modify": {
                    "type": "ModifyOrder",
                    "id": 3
                },
                "heartbeat": {
                    "type": "Heartbeat",
                    "id": 4
                },
                "mc": {
                    "type": "MassCancel",
                    "id": 5
                }
            }
        },
        "NewOrder": {
            "oneofs": {
                "_price": {
                    "oneof": [
                        "price"
                    ]
                },
                "_selfTradePrevention": {
                    "oneof": [
                        "selfTradePrevention"
                    ]
                }
            },
            "fields": {
                "clientOrderId": {
                    "type": "uint64",
                    "id": 1
                },
                "requestId": {
                    "type": "uint64",
                    "id": 2
                },
                "marketId": {
                    "type": "uint64",
                    "id": 3
                },
                "price": {
                    "type": "uint64",
                    "id": 4,
                    "options": {
                        "proto3_optional": true
                    }
                },
                "quantity": {
                    "type": "uint64",
                    "id": 5
                },
                "side": {
                    "type": "Side",
                    "id": 6
                },
                "timeInForce": {
                    "type": "TimeInForce",
                    "id": 7
                },
                "orderType": {
                    "type": "OrderType",
                    "id": 8
                },
                "subaccountId": {
                    "type": "uint64",
                    "id": 9
                },
                "selfTradePrevention": {
                    "type": "SelfTradePrevention",
                    "id": 10,
                    "options": {
                        "proto3_optional": true
                    }
                },
                "postOnly": {
                    "type": "PostOnly",
                    "id": 11
                },
                "cancelOnDisconnect": {
                    "type": "bool",
                    "id": 12
                }
            }
        },
        "CancelOrder": {
            "fields": {
                "marketId": {
                    "type": "uint64",
                    "id": 1
                },
                "clientOrderId": {
                    "type": "uint64",
                    "id": 2
                },
                "requestId": {
                    "type": "uint64",
                    "id": 3
                },
                "subaccountId": {
                    "type": "uint64",
                    "id": 4
                }
            }
        },
        "ModifyOrder": {
            "oneofs": {
                "_selfTradePrevention": {
                    "oneof": [
                        "selfTradePrevention"
                    ]
                }
            },
            "fields": {
                "marketId": {
                    "type": "uint64",
                    "id": 1
                },
                "clientOrderId": {
                    "type": "uint64",
                    "id": 2
                },
                "requestId": {
                    "type": "uint64",
                    "id": 3
                },
                "newPrice": {
                    "type": "uint64",
                    "id": 4
                },
                "newQuantity": {
                    "type": "uint64",
                    "id": 5
                },
                "subaccountId": {
                    "type": "uint64",
                    "id": 6
                },
                "selfTradePrevention": {
                    "type": "SelfTradePrevention",
                    "id": 7,
                    "options": {
                        "proto3_optional": true
                    }
                },
                "postOnly": {
                    "type": "PostOnly",
                    "id": 8
                }
            }
        },
        "MassCancel": {
            "oneofs": {
                "_marketId": {
                    "oneof": [
                        "marketId"
                    ]
                },
                "_side": {
                    "oneof": [
                        "side"
                    ]
                }
            },
            "fields": {
                "subaccountId": {
                    "type": "uint64",
                    "id": 1
                },
                "requestId": {
                    "type": "uint64",
                    "id": 2
                },
                "marketId": {
                    "type": "uint64",
                    "id": 3,
                    "options": {
                        "proto3_optional": true
                    }
                },
                "side": {
                    "type": "Side",
                    "id": 4,
                    "options": {
                        "proto3_optional": true
                    }
                }
            }
        },
        "Heartbeat": {
            "fields": {
                "requestId": {
                    "type": "uint64",
                    "id": 1
                },
                "timestamp": {
                    "type": "uint64",
                    "id": 2
                }
            }
        },
        "OrderResponse": {
            "oneofs": {
                "inner": {
                    "oneof": [
                        "newAck",
                        "cancelAck",
                        "modifyAck",
                        "newReject",
                        "cancelReject",
                        "modifyReject",
                        "fill",
                        "heartbeat",
                        "position",
                        "massCancelAck",
                        "tradingStatus"
                    ]
                }
            },
            "fields": {
                "newAck": {
                    "type": "NewOrderAck",
                    "id": 1
                },
                "cancelAck": {
                    "type": "CancelOrderAck",
                    "id": 2
                },
                "modifyAck": {
                    "type": "ModifyOrderAck",
                    "id": 3
                },
                "newReject": {
                    "type": "NewOrderReject",
                    "id": 4
                },
                "cancelReject": {
                    "type": "CancelOrderReject",
                    "id": 5
                },
                "modifyReject": {
                    "type": "ModifyOrderReject",
                    "id": 6
                },
                "fill": {
                    "type": "Fill",
                    "id": 7
                },
                "heartbeat": {
                    "type": "Heartbeat",
                    "id": 8
                },
                "position": {
                    "type": "AssetPosition",
                    "id": 9
                },
                "massCancelAck": {
                    "type": "MassCancelAck",
                    "id": 10
                },
                "tradingStatus": {
                    "type": "TradingStatus",
                    "id": 11
                }
            }
        },
        "NewOrderAck": {
            "oneofs": {
                "_price": {
                    "oneof": [
                        "price"
                    ]
                }
            },
            "fields": {
                "msgSeqNum": {
                    "type": "uint64",
                    "id": 1
                },
                "clientOrderId": {
                    "type": "uint64",
                    "id": 2
                },
                "requestId": {
                    "type": "uint64",
                    "id": 3
                },
                "exchangeOrderId": {
                    "type": "uint64",
                    "id": 4
                },
                "marketId": {
                    "type": "uint64",
                    "id": 5
                },
                "price": {
                    "type": "uint64",
                    "id": 6,
                    "options": {
                        "proto3_optional": true
                    }
                },
                "quantity": {
                    "type": "uint64",
                    "id": 7
                },
                "side": {
                    "type": "Side",
                    "id": 8
                },
                "timeInForce": {
                    "type": "TimeInForce",
                    "id": 9
                },
                "orderType": {
                    "type": "OrderType",
                    "id": 10
                },
                "transactTime": {
                    "type": "uint64",
                    "id": 11
                },
                "subaccountId": {
                    "type": "uint64",
                    "id": 12
                },
                "cancelOnDisconnect": {
                    "type": "bool",
                    "id": 13
                }
            }
        },
        "CancelOrderAck": {
            "fields": {
                "msgSeqNum": {
                    "type": "uint64",
                    "id": 1
                },
                "clientOrderId": {
                    "type": "uint64",
                    "id": 2
                },
                "requestId": {
                    "type": "uint64",
                    "id": 3
                },
                "transactTime": {
                    "type": "uint64",
                    "id": 4
                },
                "subaccountId": {
                    "type": "uint64",
                    "id": 5
                },
                "reason": {
                    "type": "Reason",
                    "id": 6
                },
                "marketId": {
                    "type": "uint64",
                    "id": 7
                },
                "exchangeOrderId": {
                    "type": "uint64",
                    "id": 8
                }
            },
            "nested": {
                "Reason": {
                    "values": {
                        "UNCLASSIFIED": 0,
                        "DISCONNECT": 1,
                        "REQUESTED": 2,
                        "IOC": 3,
                        "STP_RESTING": 4,
                        "STP_AGGRESSING": 5,
                        "MASS_CANCEL": 6,
                        "POSITION_LIMIT": 7
                    }
                }
            }
        },
        "ModifyOrderAck": {
            "fields": {
                "msgSeqNum": {
                    "type": "uint64",
                    "id": 1
                },
                "clientOrderId": {
                    "type": "uint64",
                    "id": 2
                },
                "requestId": {
                    "type": "uint64",
                    "id": 3
                },
                "transactTime": {
                    "type": "uint64",
                    "id": 4
                },
                "remainingQuantity": {
                    "type": "uint64",
                    "id": 5
                },
                "subaccountId": {
                    "type": "uint64",
                    "id": 6
                },
                "marketId": {
                    "type": "uint64",
                    "id": 7
                },
                "price": {
                    "type": "uint64",
                    "id": 8
                },
                "quantity": {
                    "type": "uint64",
                    "id": 9
                },
                "cumulativeQuantity": {
                    "type": "uint64",
                    "id": 10
                },
                "exchangeOrderId": {
                    "type": "uint64",
                    "id": 11
                }
            }
        },
        "MassCancelAck": {
            "oneofs": {
                "_reason": {
                    "oneof": [
                        "reason"
                    ]
                }
            },
            "fields": {
                "msgSeqNum": {
                    "type": "uint64",
                    "id": 1
                },
                "subaccountId": {
                    "type": "uint64",
                    "id": 2
                },
                "requestId": {
                    "type": "uint64",
                    "id": 3
                },
                "transactTime": {
                    "type": "uint64",
                    "id": 4
                },
                "reason": {
                    "type": "Reason",
                    "id": 6,
                    "options": {
                        "proto3_optional": true
                    }
                },
                "totalAffectedOrders": {
                    "type": "uint32",
                    "id": 7
                }
            },
            "nested": {
                "Reason": {
                    "values": {
                        "UNCLASSIFIED": 0,
                        "INVALID_MARKET_ID": 1,
                        "INVALID_SIDE": 2
                    }
                }
            }
        },
        "NewOrderReject": {
            "oneofs": {
                "_price": {
                    "oneof": [
                        "price"
                    ]
                }
            },
            "fields": {
                "msgSeqNum": {
                    "type": "uint64",
                    "id": 1
                },
                "clientOrderId": {
                    "type": "uint64",
                    "id": 2
                },
                "requestId": {
                    "type": "uint64",
                    "id": 3
                },
                "transactTime": {
                    "type": "uint64",
                    "id": 4
                },
                "subaccountId": {
                    "type": "uint64",
                    "id": 5
                },
                "reason": {
                    "type": "Reason",
                    "id": 6
                },
                "marketId": {
                    "type": "uint64",
                    "id": 7
                },
                "price": {
                    "type": "uint64",
                    "id": 8,
                    "options": {
                        "proto3_optional": true
                    }
                },
                "quantity": {
                    "type": "uint64",
                    "id": 9
                },
                "side": {
                    "type": "Side",
                    "id": 10
                },
                "timeInForce": {
                    "type": "TimeInForce",
                    "id": 11
                },
                "orderType": {
                    "type": "OrderType",
                    "id": 12
                }
            },
            "nested": {
                "Reason": {
                    "values": {
                        "UNCLASSIFIED": 0,
                        "INVALID_QUANTITY": 1,
                        "INVALID_MARKET_ID": 2,
                        "DUPLICATE_ORDER_ID": 3,
                        "INVALID_SIDE": 4,
                        "INVALID_TIME_IN_FORCE": 5,
                        "INVALID_ORDER_TYPE": 6,
                        "INVALID_POST_ONLY": 7,
                        "INVALID_SELF_TRADE_PREVENTION": 8,
                        "UNKNOWN_TRADER": 9,
                        "PRICE_WITH_MARKET_LIMIT_ORDER": 10,
                        "POST_ONLY_WITH_MARKET_ORDER": 11,
                        "POST_ONLY_WITH_INVALID_TIF": 12,
                        "EXCEEDED_SPOT_POSITION": 13,
                        "NO_OPPOSING_RESTING_ORDER": 14,
                        "POST_ONLY_WOULD_TRADE": 15,
                        "DID_NOT_FULLY_FILL": 16,
                        "ONLY_ORDER_CANCEL_ACCEPTED": 17,
                        "PROTECTION_PRICE_WOULD_NOT_TRADE": 18,
                        "NO_REFERENCE_PRICE": 19,
                        "SLIPPAGE_TOO_HIGH": 20,
                        "OUTSIDE_PRICE_BAND": 21
                    }
                }
            }
        },
        "CancelOrderReject": {
            "fields": {
                "msgSeqNum": {
                    "type": "uint64",
                    "id": 1
                },
                "clientOrderId": {
                    "type": "uint64",
                    "id": 2
                },
                "requestId": {
                    "type": "uint64",
                    "id": 3
                },
                "transactTime": {
                    "type": "uint64",
                    "id": 4
                },
                "subaccountId": {
                    "type": "uint64",
                    "id": 5
                },
                "reason": {
                    "type": "Reason",
                    "id": 6
                },
                "marketId": {
                    "type": "uint64",
                    "id": 7
                }
            },
            "nested": {
                "Reason": {
                    "values": {
                        "UNCLASSIFIED": 0,
                        "INVALID_MARKET_ID": 1,
                        "ORDER_NOT_FOUND": 2
                    }
                }
            }
        },
        "ModifyOrderReject": {
            "fields": {
                "msgSeqNum": {
                    "type": "uint64",
                    "id": 1
                },
                "clientOrderId": {
                    "type": "uint64",
                    "id": 2
                },
                "requestId": {
                    "type": "uint64",
                    "id": 3
                },
                "transactTime": {
                    "type": "uint64",
                    "id": 4
                },
                "subaccountId": {
                    "type": "uint64",
                    "id": 5
                },
                "reason": {
                    "type": "Reason",
                    "id": 6
                },
                "marketId": {
                    "type": "uint64",
                    "id": 7
                }
            },
            "nested": {
                "Reason": {
                    "values": {
                        "UNCLASSIFIED": 0,
                        "INVALID_QUANTITY": 1,
                        "INVALID_MARKET_ID": 2,
                        "ORDER_NOT_FOUND": 3,
                        "INVALID_IFM": 4,
                        "INVALID_POST_ONLY": 5,
                        "INVALID_SELF_TRADE_PREVENTION": 6,
                        "UNKNOWN_TRADER": 7,
                        "EXCEEDED_SPOT_POSITION": 8,
                        "POST_ONLY_WOULD_TRADE": 9,
                        "ONLY_ORDER_CANCEL_ACCEPTED": 17,
                        "OUTSIDE_PRICE_BAND": 11
                    }
                }
            }
        },
        "Fill": {
            "fields": {
                "msgSeqNum": {
                    "type": "uint64",
                    "id": 1
                },
                "marketId": {
                    "type": "uint64",
                    "id": 2
                },
                "clientOrderId": {
                    "type": "uint64",
                    "id": 3
                },
                "exchangeOrderId": {
                    "type": "uint64",
                    "id": 4
                },
                "fillPrice": {
                    "type": "uint64",
                    "id": 5
                },
                "fillQuantity": {
                    "type": "uint64",
                    "id": 6
                },
                "leavesQuantity": {
                    "type": "uint64",
                    "id": 7
                },
                "fillQuoteQuantity": {
                    "type": "uint64",
                    "id": 15
                },
                "transactTime": {
                    "type": "uint64",
                    "id": 8
                },
                "subaccountId": {
                    "type": "uint64",
                    "id": 9
                },
                "cumulativeQuantity": {
                    "type": "uint64",
                    "id": 10
                },
                "side": {
                    "type": "Side",
                    "id": 11
                },
                "aggressorIndicator": {
                    "type": "bool",
                    "id": 12
                },
                "feeRatio": {
                    "type": "FixedPointDecimal",
                    "id": 13
                },
                "tradeId": {
                    "type": "uint64",
                    "id": 14
                }
            }
        },
        "FixedPointDecimal": {
            "fields": {
                "mantissa": {
                    "type": "int64",
                    "id": 1
                },
                "exponent": {
                    "type": "int32",
                    "id": 2
                }
            }
        },
        "AssetPosition": {
            "fields": {
                "subaccountId": {
                    "type": "uint64",
                    "id": 1
                },
                "assetId": {
                    "type": "uint64",
                    "id": 2
                },
                "total": {
                    "type": "RawUnits",
                    "id": 3
                },
                "available": {
                    "type": "RawUnits",
                    "id": 4
                }
            }
        },
        "RawUnits": {
            "fields": {
                "word0": {
                    "type": "uint64",
                    "id": 1
                },
                "word1": {
                    "type": "uint64",
                    "id": 2
                },
                "word2": {
                    "type": "uint64",
                    "id": 3
                },
                "word3": {
                    "type": "uint64",
                    "id": 4
                }
            }
        },
        "Bootstrap": {
            "oneofs": {
                "inner": {
                    "oneof": [
                        "done",
                        "resting",
                        "position",
                        "tradingStatus"
                    ]
                }
            },
            "fields": {
                "done": {
                    "type": "Done",
                    "id": 1
                },
                "resting": {
                    "type": "RestingOrders",
                    "id": 2
                },
                "position": {
                    "type": "AssetPositions",
                    "id": 3
                },
                "tradingStatus": {
                    "type": "TradingStatus",
                    "id": 4
                }
            }
        },
        "RestingOrders": {
            "fields": {
                "orders": {
                    "rule": "repeated",
                    "type": "RestingOrder",
                    "id": 1
                }
            }
        },
        "AssetPositions": {
            "fields": {
                "positions": {
                    "rule": "repeated",
                    "type": "AssetPosition",
                    "id": 1
                }
            }
        },
        "Done": {
            "fields": {
                "latestTransactTime": {
                    "type": "uint64",
                    "id": 1
                },
                "readOnly": {
                    "type": "bool",
                    "id": 2
                }
            }
        },
        "TradingStatus": {
            "fields": {
                "connectionStatus": {
                    "type": "ConnectionStatus",
                    "id": 1
                }
            }
        },
        "RestingOrder": {
            "fields": {
                "clientOrderId": {
                    "type": "uint64",
                    "id": 1
                },
                "exchangeOrderId": {
                    "type": "uint64",
                    "id": 2
                },
                "marketId": {
                    "type": "uint64",
                    "id": 3
                },
                "price": {
                    "type": "uint64",
                    "id": 4
                },
                "orderQuantity": {
                    "type": "uint64",
                    "id": 5
                },
                "side": {
                    "type": "Side",
                    "id": 6
                },
                "timeInForce": {
                    "type": "TimeInForce",
                    "id": 7
                },
                "orderType": {
                    "type": "OrderType",
                    "id": 8
                },
                "remainingQuantity": {
                    "type": "uint64",
                    "id": 9
                },
                "restTime": {
                    "type": "uint64",
                    "id": 10
                },
                "subaccountId": {
                    "type": "uint64",
                    "id": 11
                },
                "cumulativeQuantity": {
                    "type": "uint64",
                    "id": 12
                },
                "cancelOnDisconnect": {
                    "type": "bool",
                    "id": 13
                }
            }
        }
    }
};

const marketDataRoot = protobuf.Root.fromJSON(marketDataProtoDefinitions);
const tradeRoot  = protobuf.Root.fromJSON(tradeProtoDefinitions)

const AssetPosition = tradeRoot.lookupType('AssetPosition');
const AssetPositions = tradeRoot.lookupType('AssetPositions');
const Bootstrap = tradeRoot.lookupType('Bootstrap');
const CancelOrder = tradeRoot.lookupType('CancelOrder');
const CancelOrderAck = tradeRoot.lookupType('CancelOrderAck');
const CancelOrderReject = tradeRoot.lookupType('CancelOrderReject');
const Credentials = tradeRoot.lookupType('Credentials');
const Done = tradeRoot.lookupType('Done');
const Fill = tradeRoot.lookupType('Fill');
const FixedPointDecimal = tradeRoot.lookupType('FixedPointDecimal');
// const Heartbeat = root.lookupType('Heartbeat');
const MassCancel = tradeRoot.lookupType('MassCancel');
const MassCancelAck = tradeRoot.lookupType('MassCancelAck');
const ModifyOrder = tradeRoot.lookupType('ModifyOrder');
const ModifyOrderAck = tradeRoot.lookupType('ModifyOrderAck');
const ModifyOrderReject = tradeRoot.lookupType('ModifyOrderReject');
const NewOrder = tradeRoot.lookupType('NewOrder');
const NewOrderAck = tradeRoot.lookupType('NewOrderAck');
const NewOrderReject = tradeRoot.lookupType('NewOrderReject');
const OrderRequest = tradeRoot.lookupType('OrderRequest');
const OrderResponse = tradeRoot.lookupType('OrderResponse');
const RawUnits = tradeRoot.lookupType('RawUnits');
const RestingOrder = tradeRoot.lookupType('RestingOrder');
const RestingOrders = tradeRoot.lookupType('RestingOrders');
const TradingStatus = tradeRoot.lookupType('TradingStatus');

const AggMessage = marketDataRoot.lookupType('AggMessage');
const ClientMessage = marketDataRoot.lookupType('ClientMessage');
const Config = marketDataRoot.lookupType('Config');
const Heartbeat = marketDataRoot.lookupType('Heartbeat');
const Kline = marketDataRoot.lookupType('Kline');
const MarketByOrder = marketDataRoot.lookupType('MarketByOrder');
const MarketByOrderDiff = marketDataRoot.lookupType('MarketByOrderDiff');
const MarketByPrice = marketDataRoot.lookupType('MarketByPrice');
const MarketByPriceDiff = marketDataRoot.lookupType('MarketByPriceDiff');
const MarketStatus = marketDataRoot.lookupType('MarketStatus');
const MdMessage = marketDataRoot.lookupType('MdMessage');
const MdMessages = marketDataRoot.lookupType('MdMessages');
const RateUpdate = marketDataRoot.lookupType('RateUpdate');
const RateUpdates = marketDataRoot.lookupType('RateUpdates');
const Summary = marketDataRoot.lookupType('Summary');
const TopOfBook = marketDataRoot.lookupType('TopOfBook');
const TopOfBooks = marketDataRoot.lookupType('TopOfBooks');
const Trades = marketDataRoot.lookupType('Trades');


export default class cube extends cubeRest {
    constructor (userConfig = {}) {
        super (userConfig);

        this.verbose = true;
    }

    describe() {
        return this.deepExtend(super.describe(), {
            'has': {
                'ws': true,
                'cancelOrderWs': false,
                'cancelOrdersWs': false,
                'cancelAllOrdersWs': false,
                'createOrderWs': true,
                'editOrderWs': false,
                'fetchBalanceWs': false,
                'fetchDepositsWs': false,
                'fetchMarketsWs': false,
                'fetchMyTradesWs': false,
                'fetchOHLCVWs': false,
                'fetchOpenOrdersWs': false,
                'fetchOrderWs': false,
                'fetchOrdersWs': false,
                'fetchTradesWs': false,
                'fetchTradingFeesWs': false,
                'fetchWithdrawalsWs': false,
                'watchBalance': false,
                'watchMyTrades': false,
                'watchOHLCV': false,
                'watchOHLCVForSymbols': false,
                'watchOrderBook': true,
                'watchOrderBookForSymbols': false,
                'watchOrders': false,
                'watchOrdersForSymbols': false,
                'watchPositions': false,
                'watchTicker': false,
                'watchTickers': false,
                'watchTrades': false,
                'watchTradesForSymbols': false,
            },
            'options': {
                'ws': {
                    'staging': {
                        'mendelev': {
                            'public': {
                                'orderbook': '/book/{marketId}',
                                'orderbookTops': '/tops',
                            },
                        },
                        'osmium': {
                            'private': {
                                'root': '/',
                            },
                        },
                    },
                    'cost': 5,
                },
            },
        });
    }

    getWebsocketUrl (system, privacy, path, params = {}) {
        const environment = this.options['environment'];
        path = this.implodeParams (path, params);
        return this.urls['api']['ws'][environment][system] + this.options['ws'][environment][system][privacy][path];
    }

    async watchOrderBook (symbol, limit = undefined, params = {}) {
        /**
         * @method
         * @name cube#watchOrderBook
         * @description watches information on open orders with bid (buy) and ask (sell) prices, volumes and other data
         * @see https://cubexch.gitbook.io/cube-api/websocket-market-data-api#order-book-data
         * @param {string} symbol unified symbol of the market to fetch the order book for
         * @param {int} [limit] the maximum amount of order book entries to return
         * @param {object} [params] extra parameters specific to the exchange API endpoint
         * @returns {object} A dictionary of [order book structures]{@link https://docs.ccxt.com/#/?id=order-book-structure} indexed by market symbols
         */
        // const url = this.getWebsocketUrl ('osmium', 'private', 'root', { 'marketId': marketId });
        const url = 'wss://staging.cube.exchange/md/book/200047?trades=true&summary=true&mbo=true';

        const configMessage = Config.create({
            klines: [0],
            marketIds: [],
            mbo: true,
            trades: true,
            summary: true
        });

        const clientMessage = ClientMessage.create({
            config: configMessage
        });

        const clientMessageBuffer = ClientMessage.encode(clientMessage).finish();

        const message = clientMessageBuffer;
        const messageHash = 'clientMessage';
        const subscribeHash = messageHash;
        const subscription = {
            'method': this.handleOrderBook,
        };
        return await this.watch(url, messageHash, message, subscribeHash, subscription);
    }

    handleOrderBook (client, message) {
        try {
            console.log('handleOrderBook:', JSON.stringify(MdMessages.decode(message)));
        } catch (error) {
            console.log(error);
        }
    }

    async watchTicker (symbol, params = {}){
        /**
         * @method
         * @name cube#watchTicker
         * @description watches a price ticker, a statistical calculation with the information calculated over the past 24 hours for a specific market
         * @param {string} symbol unified symbol of the market to fetch the ticker for
         * @param {object} [params] extra parameters specific to the exchange API endpoint
         * @returns {object} a [ticker structure]{@link https://docs.ccxt.com/#/?id=ticker-structure}
         */
        return null;
    }

    handleTicker (client, message) {}

    parseTicker (ticker, market = undefined){
        return null;
    }

    async watchOHLCV (symbol, timeframe = '1m', since = undefined, limit = undefined, params = {}) {
        /**
         * @method
         * @name cube#watchOHLCV
         * @description watches historical candlestick data containing the open, high, low, and close price, and the volume of a market
         * @param {string} symbol unified symbol of the market to fetch OHLCV data for
         * @param {string} timeframe the length of time each candle represents
         * @param {int} [since] timestamp in ms of the earliest candle to fetch
         * @param {int} [limit] the maximum amount of candles to fetch
         * @param {object} [params] extra parameters specific to the exchange API endpoint
         * @returns {int[][]} A list of candles ordered as timestamp, open, high, low, close, volume
         */
        const url = this.getWebsocketUrl ('mendelev', 'public', 'orderbook');
        // await this.authenticate (url);
        await this.loadMarkets ();
        const market = this.market (symbol);
        symbol = market['symbol'];
        const messageHash = 'ohlcv:' + symbol;   // ???
        const request = {};
        const ohlcv = await this.watch (url, messageHash, this.extend (request, params), messageHash);
        if (this.newUpdates) {
            limit = ohlcv.getLimit (symbol, limit);
        }
        return this.filterBySinceLimit (ohlcv, since, limit, 0, true);
    }

    handleOHLCV (client, message) {
        //
        //    {
        //        "endtime": 1714423464,
        //        "interval": "15m",
        //        "limit": 1000,
        //        "marketId": 200047,
        //        "startTime": 1714122864,
        //    }
        //
        const marketId = this.safeString (message, 'marketId');
        const symbol = this.safeSymbol (marketId);
        const data = {};
        const interval = this.safeString (data, 'interval');
        const request = {
            symbol,
            interval,
        };
        return request;
    }

    async watchTrades (symbol, since = undefined, limit = undefined, params = {}){
        /**
         * @method
         * @name cube#watchTrades
         * @description watches information on multiple trades made in a market
         * @param {string} symbol unified market symbol of the market trades were made in
         * @param {int} [since] the earliest time in ms to fetch orders for
         * @param {int} [limit] the maximum number of trade structures to retrieve
         * @param {object} [params] extra parameters specific to the exchange API endpoint
         * @returns {object[]} a list of [trade structures]{@link https://docs.ccxt.com/#/?id=trade-structure}
         */
        return null;   
    }

    handleTrades (client, message) {}

    async watchOrders (symbol = undefined, since = undefined, limit = undefined, params = {}) {
        /**
         * @method
         * @name cube#watchOrders
         * @description watches information on multiple orders made by the user
         * @param {string} symbol unified market symbol of the market orders were made in
         * @param {int} [since] the earliest time in ms to fetch orders for
         * @param {int} [limit] the maximum number of order structures to retrieve
         * @param {object} [params] extra parameters specific to the exchange API endpoint
         * @returns {object[]} a list of [order structures]{@link https://docs.ccxt.com/#/?id=order-structure}
         */
        return null;
    }

    handleOrder (client, message) {}

    async watchMyTrades (symbol = undefined, since = undefined, limit = undefined, params = {}) {
        /**
         * @method
         * @name cube#watchMyTrades
         * @description watches information on multiple trades made by the user
         * @param {string} symbol unified market symbol of the market trades were made in
         * @param {int} [since] the earliest time in ms to fetch trades for
         * @param {int} [limit] the maximum number of trade structures to retrieve
         * @param {object} [params] extra parameters specific to the exchange API endpoint
         * @param {boolean} [params.unifiedMargin] use unified margin account
         * @returns {object[]} a list of [trade structures]{@link https://docs.ccxt.com/#/?id=trade-structure}
         */
        return null;
    }

    async watchBalance (params = {}){
        /**
         * @method
         * @name cube#watchBalance
         * @description watch balance and get the amount of funds available for trading or funds locked in orders
         * @param {object} [params] extra parameters specific to the exchange API endpoint
         * @param {boolean} [params.portfolioMargin] set to true if you would like to watch the balance of a portfolio margin account
         * @returns {object} a [balance structure]{@link https://docs.ccxt.com/#/?id=balance-structure}
         */
        return null;
    }

    handleBalance(client, message) {}

    async onConnected (client, message = undefined) {
        try {
            console.log ('onConnected', message);
        } catch (e) {
            console.log(e);
        }
    }

    async handleMessage (client, message) {
        try {
            console.log('handleOrderBook:', JSON.stringify(MdMessages.decode(message)));
            // console.log ('handleMessage', this.uint8ArrayToBase64 (message), message);
        } catch (e) {
            console.log(e);
        }
    }

    uint8ArrayToHex(array) {
        return Array.from(array).map(b => b.toString(16).padStart(2, '0')).join('');
    }

    uint8ArrayToBase64(array) {
        const binaryString = array.reduce((acc, byte) => acc + String.fromCharCode(byte), '');
        return btoa(binaryString);
    }

    hexToUint8Array(hexString) {
        const length = hexString.length / 2;
        const array = new Uint8Array(length);
        for (let i = 0; i < length; i++) {
            const hexByte = hexString.substr(i * 2, 2);
            array[i] = parseInt(hexByte, 16);
        }
        return array;
    }

    base64ToUint8Array(base64String) {
        const binaryString = atob(base64String);
        const length = binaryString.length;
        const array = new Uint8Array(length);
        for (let i = 0; i < length; i++) {
            array[i] = binaryString.charCodeAt(i);
        }
        return array;
    }

    async createOrderWs (symbol, type, side, amount, price = undefined, params = {}) {
        /**
         * @method
         * @name binance#createOrderWs
         * @see https://cubexch.gitbook.io/cube-api/websocket-trade-api#orderrequest
         * @description create an order
         * @param {string} symbol unified symbol of the market to create an order in
         * @param {string} type 'market' or 'limit'
         * @param {string} side 'buy' or 'sell'
         * @param {float} amount how much of currency you want to trade in units of base currency
         * @param {float|undefined} [price] the price at which the order is to be fullfilled, in units of the quote currency, ignored in market orders
         * @param {object} [params] extra parameters specific to the exchange API endpoint
         * @param {boolean} params.test test order, default false
         * @returns {object} an [order structure]{@link https://docs.ccxt.com/#/?id=order-structure}
         */
        const meta = await this.fetchMarketMeta (symbol);
        symbol = this.safeString (meta, 'symbol');
        const marketId = this.safeString (meta, 'marketId');
        const market = this.safeDict(meta, 'market');
        const quantityTickSize = this.safeNumber(this.safeDict(market, 'info'), 'quantityTickSize');
        const priceTickSize = this.safeNumber(this.safeDict(market, 'info'), 'priceTickSize');
        const exchangeAmount = this.parseToInt(amount / quantityTickSize);
        let exchangePrice = undefined;
        if (price !== undefined) {
            exchangePrice = this.parseToInt(price / priceTickSize);
        }
        let exchangeOrderType = undefined;
        if (type === 'limit') {
            exchangeOrderType = 0;
        }
        else if (type === 'market') {
            exchangeOrderType = 1;
        }
        else if (type === 'MARKET_WITH_PROTECTION') {
            exchangeOrderType = 2;
        }
        else {
            throw new InvalidOrder('OrderType was not recognized: ' + type);
        }
        let exchangeOrderSide = undefined;
        if (side === 'buy') {
            exchangeOrderSide = 0;
        }
        else if (side === 'sell') {
            exchangeOrderSide = 1;
        }
        else {
            throw new InvalidOrder('OrderSide was not recognized: ' + side);
        }
        const timestamp = this.milliseconds();
        const clientOrderIdFromParams = this.safeInteger(params, 'clientOrderId');
        let clientOrderId = undefined;
        if (clientOrderIdFromParams === undefined) {
            clientOrderId = timestamp;
        }
        else {
            clientOrderId = clientOrderIdFromParams;
        }
        const url = this.getWebsocketUrl ('osmium', 'private', 'root', { 'marketId': marketId });

        // const clinet = this.clinet(url)
        const client = new Client(url);

        const credentialsMessage = Credentials.create({
            accessKeyId: this.apiKey,
            signature: this.generateSignature()[0],
            timestamp: timestamp
        });
        const credentialsBuffer = Credentials.encode(credentialsMessage).finish();

        await client.send(credentialsBuffer)

        const newOrder = NewOrder.create({
            clientOrderId: timestamp,
            requestId: 1,
            marketId: marketId,
            price: exchangePrice,
            quantity: exchangeAmount,
            side: exchangeOrderSide,
            timeInForce: 1,
            orderType: exchangeOrderType,
            subaccountId: this.safeInteger(this.options, 'subaccountId'),
            postOnly: 1,
            cancelOnDisconnect: false
        });

        const heartbeat = Heartbeat.create({
            requestId: 1,
            timestamp: timestamp,
        });

        const orderRequest = OrderRequest.create({
            new: newOrder,
            heartbeat: heartbeat,
        });

        const buffer = OrderRequest.encode(orderRequest).finish();

        // const watch = await this.watch(url, 'message', buffer, 'credentials', credentialsMessage);

        console.log(buffer)
    }

    handleOrderWs (client, message) {}
}
